### ISSUE TITLE
#include "string.h" missing

### ISSUE THREAD

**Issue by nasato** [ParticulateFlow/LIGGGHTS-PFM#1]
Hi old colleagues,

There might be a #include "string.h" missing in compute_com_molecule.cpp in the latest version (PFM 20.09). I could not compile without adding it.

All the best, Daniel

**Comment by schrummy14** [comment]
Hello,
How are you compiling the code?
I doubled check with my install using 
make fedora 
and found no issues.

**Comment by danielque** [comment]
Thanks for the report. Probably, many compilers will make correct assumptions about the function prototype and then automatically link the library, but strictly speaking we should include string.h due to the usage of `strcmp`. Will be fixed in the next release.

**Comment by nasato** [comment]
> Hello,
> How are you compiling the code?
> I doubled check with my install using
> make fedora
> and found no issues.

Hi,

I built it using cmake (v. 3.9.0) in CentOS 7.4

**Comment by danielque** [comment]
Fixed in d34544911fd9ec730455c3a35b12cf1370e6617d
