### ISSUE TITLE
Coarse grained method applied in heat conduction model

### ISSUE THREAD

**Issue by ChevalierXD** [ParticulateFlow/LIGGGHTS-PFM#10]
Hello,

I am trying to use the LIGGGHTS-PFM 21.11 to model coarse-grained particles in terms of flow and heat transfer process, but I failed to implement the model on LIGGGGHTS. The error is reported as:
"ERROR: The following model does not yield consistent results with coarse-graining: heat/gran (/home/561/dx4858/CFDEM/LIGGGHTS/src/fix_heat_gran_conduction.cpp:202)"

The notable changes of the version have mentioned that the coarse-graining factors in scalar transport equation (e.g. used for heat conduction) have been fixed. Therefore, I want to know whether the version can support coarse-grained method in heat transfer models and how to implement it properly.

Many thanks for your time and help.
Best regards.
Dan

**Comment by danielque** [comment]
You may add the option `model_check warn` to the `coarsegraining` command in your input script to turn the error into a warning.
The reason for the error/warning in the first place is that heat transfer doesn't scale exactly when applying the coarse graining model, however, the behavior is quite similar.

**Comment by ChevalierXD** [comment]
Many thanks for your help and time.

Best regards,
Dan
