### ISSUE TITLE
How to run the run.config in the example cases

### ISSUE THREAD

**Issue by ChevalierXD** [ParticulateFlow/LIGGGHTS-PFM#13]
Hi,

I am recently learning the example case of the multisphere/creat_clump. I know I have to run the in.create_clump first to generate the particle data and then run the in.multisphere. Firstly, I use the command "liggghts < in.create_clump" to run the task 1, but it does not work. I notice there is a file with the name of run.config. I do not know how to run the files. Can you help me in running the cases? Many thanks for your help and time.

Best regards,
Dan

**Comment by danielque** [comment]
What exactly do you mean by "it does not work"? What is the error you get?
Note that the `create_multisphere_clump` command used in _in.create_clump_ requires LIGGGHTS to be linked to the VTK library (e.g. compile with a Makefile similar to [Makefile.ubuntuVTK63](https://github.com/ParticulateFlow/LIGGGHTS-PFM/blob/master/src/MAKE/Makefile.ubuntuVTK63) or via CMake which should find the VTK SDK automatically if it is installed).
To run the example, simply use
`path/to/liggghts -in  in.create_clump`
Followed by
`path/to/liggghts -in in.multisphere`
or for parallel execution
`mpirun -np 4 path/to/liggghts -in in.multisphere`
The _run.config_ file is only useful for the automated testing system we are using internally and at best may give you some hints on how the example is meant to be executed.
