### ISSUE TITLE
Issue with super-quadric particle simulation

### ISSUE THREAD

**Issue by ifzalhussain** [ParticulateFlow/LIGGGHTS-PFM#15]
Hello,
 I am trying to do a simulation using superquadric particles. but it is showing error for the 'atom_style' command , then I tried the given example of superquadric particle in the package but it was also showing same error. To check if the mistake is on my end,  I have ran the same simulation in two different computers, but they also end up with same error. Would you be able to look at the issue and reply me with a possible fix.

thanks.

**Comment by danielque** [comment]
Did you compile LIGGGHTS with superquadrics enabled? See section 8 of the [manual](https://github.com/ParticulateFlow/LIGGGHTS-PFM/releases/download/24.01/liggghts-doc-24.01.zip) "How-to for superquadric particles"
If compiled correctly, what case did you try to run and what was the exact error message you got? For me all of the superquadric cases (fill_cylinder, particle_mesh_wall, particle_primitive_wall, particle_particle) seem to work fine.

**Comment by ifzalhussain** [comment]
thanks alot, the issue is sorted. i compiled it without enabling superquadric. I have rectified my mistake. thanks alot for replying and help. I really appreciated the help.
