### ISSUE TITLE
Unexpected behavior of region command using VTK 

### ISSUE THREAD

**Issue by richpaj** [ParticulateFlow/LIGGGHTS-PFM#8]
Hello there,

if I create a region from sample.vtk (attached) using the 'region' command i.e.

region	sampleRegion  mesh/tet  file  sample.vtk  scale 1 move 0  0 0 rotate 0 0 0 units box

and attempt to remove particles from that region with:

delete_atoms   region sampleRegion  compress yes

I discover only some atoms are deleted (close to the 'acute' corners). I am wondering
therefore if the format of sample.vtk is incorrect. (Testing at differing resolutions of sample.vtk
yields the same unexpected behaviour).

The format of sample.vtk seems consistent with the following:

examples/LIGGGHTS/PFM/adaptive_resolution/bin_fill/meshes/surface2x1.vtk
examples/LIGGGHTS/Tutorials_public/mesh_tet/data/test.vtk

and where it was constructed with the following steps:

i) create geometry and mesh in Gmsh
ii) export sample.msh -> sample.stl
iii) tetgen -pk  sample.stl  ---> sample.vtk  (for pure tet mesh)

Any ideas I wonder?

Many prospective thanks,
Richard
[sample.zip](https://github.com/ParticulateFlow/LIGGGHTS-PFM/files/8310595/sample.zip)
.

**Comment by richpaj** [comment]
As a current workaround, the trapezoid can be decomposed into a primitive central rectangular block and two side wedges and where the two side wedges can be generated by the steps i)-iii) indicated above.

**Comment by danielque** [comment]
The file looks good and this works OK for me in version 23.02 ...
